- hosts: localhost
  tasks:

  - name: Global
    block:
    - name: Get repository path
      ansible.builtin.command: git rev-parse --show-toplevel
      changed_when: false
      register: repo_path_cmd
    - name: Find distro
      command: cat /etc/os-release
      register: os
    - name: Set lin
      ansible.builtin.set_fact:
        is_arch: "{{ 'arch' in os.stdout or 'manjaro' in os.stdout }}"
        is_centos: "{{ 'centos' in os.stdout }}"

  - name: Tools in arch
    when: "{{ is_arch }}"
    block:
      - name: Install dev-tools
        become: true
        community.general.pacman:
          update_cache: true
          name:
            - neovim
            - git
            - lazygit
            - taskwarrior-tui
            - task
            - terraform
            - packer
          state: present

  - name: Check tools
    block:
      - command: nvim --version
      - command: lazygit --version
      - command: terraform --version
      - command: packer --version
      - command: task --version
