[glob]
foreground         = #FFD6C0
foreground_intense = #FFFFFF
foreground_faint   = #FAE1DF

background         = #0E0718
background_darker  = #000000
background_intense = #071013
background_faint   = #000000

grey               = #565254
grey_darker        = #262224
grey_intense       = #000000
grey_faint         = #AEA3B0

red                = #E16036
red_intense        = #E3170A
red_faint          = #EB9486

magenta            = #a409b8
magenta_intense    = #ca0be3
magenta_faint      = #6c2975

green              = #22A563
green_darker       = #13683d
green_intense      = #60992D
green_faint        = #CAE7B9

yellow             = #E9EB60
yellow_intense     = #E3D063
yellow_faint       = #D4D29B

orange             = #EC7505
orange_intense     = #ff9f1c
orange_faint       = #FFBF69

blue               = #2274A5
blue_light         = #4e5ae2
blue_intense       = #4e5ae2
blue_dark          = #143379
blue_faint         = #4e5ae2

pink               = #da0bd7
pink_light         = #e30bdf
pink_intense       = #e30bdf
pink_dark          = #b809b6
pink_faint         = #b809b6

cyan               = #0b8bda
cyan_faint         = #284f76
cyan_intense       = #0b80e3

white              = #F0F0F0
white_intense      = #FFFFFF
white_faint        = #E0E0E0

black              = #000000
black_intense      = #000000
black_faint        = #202020

# black = #22242e

# purple_dark = #8d2f9d
# orange_dark =

# font_normal_size = 12

p1 = 4px
p2 = 8px
p3 = 12px
p4 = 4px4

[rofi]

# item_height = 124
# column_count = 5
# line_count = 5
# height=100

[font]
main=HasklugNerdFont-Regular.otf
zip_url=https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/Hasklig.zip
name=Hasklug Nerd Font
