-- local telescope = require('telescope')
--
-- telescope.load_extension "go_task"
-- telescope.load_extension "file_browser"
--
-- telescope.setup {
-- 	defaults = {
-- 		path_display={"smart"} 
-- 	},
-- 	pickers = {
-- 		find_files = {
-- 			find_command = { "fd", "--type", "f", "--color", "never" },
-- 			theme = "dropdown",
-- 			hidden = true
-- 		},
-- 		buffers = {
-- 		  mappings = {
-- 				i = {
-- 				  ["<C-D>"] = "delete_buffer",
-- 				}
-- 			}
-- 		}
-- 	}
-- }
--
