version: '3'

vars:
  GREETING: Hello, World!

tasks:


  install-asdf-plugins:
    cmds:
      - cmd: cat ~/.tool-versions | cut -d ' ' -f 1 | xargs -I@ bash -c 'asdf plugin-add @'
        ignore_error: true
      - asdf install
      - asdf reshim

  doctor:
    silent: true
    cmds:
      - |
        clear
        echo '
        #=====================#
        # Basic system doctor #
        #---------------------#
        '
        echo -n "Ansible install..." && ansible --version > /dev/null 2>&1 && echo "OK" || echo "KO"
        echo -n "Ansible modules..." && ansible-doc --list | grep docker > /dev/null 2>&1 && echo "OK" || echo "KO"

        echo
